"""initial mobile forum schema"""

from alembic import op
import sqlalchemy as sa

revision = "47350762dcb6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("target", sa.String(length=36), nullable=False),
        sa.Column("action", sa.String(length=30), nullable=False),
        sa.Column("note", sa.String(length=300), nullable=False),
        sa.Column("created", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "rate_buckets",
        sa.Column("key", sa.String(length=120), nullable=False),
        sa.Column("count", sa.BigInteger(), nullable=False),
        sa.Column("expires", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    with op.batch_alter_table("rate_buckets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_rate_buckets_expires"), ["expires"], unique=False
        )

    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("secret_hash", sa.String(length=64), nullable=False),
        sa.Column("created", sa.BigInteger(), nullable=False),
        sa.Column("terms", sa.String(length=32), nullable=False),
        sa.Column("banned", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("secret_hash"),
    )
    op.create_table(
        "blocks",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner", sa.String(length=36), nullable=False),
        sa.Column("target", sa.String(length=36), nullable=False),
        sa.Column("created", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["owner"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner", "target"),
    )
    op.create_table(
        "feedback",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("device", sa.String(length=150), nullable=False),
        sa.Column("app_version", sa.String(length=30), nullable=False),
        sa.Column("created", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("response", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["owner"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("feedback", schema=None) as batch_op:
        batch_op.create_index("feedback_queue", ["status", "created"], unique=False)
        batch_op.create_index(batch_op.f("ix_feedback_owner"), ["owner"], unique=False)

    op.create_table(
        "posts",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=80), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("created", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("likes", sa.BigInteger(), nullable=False),
        sa.Column("replies", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["owner"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_posts_owner"), ["owner"], unique=False)
        batch_op.create_index(
            "posts_category_feed", ["status", "category", "created", "id"], unique=False
        )
        batch_op.create_index("posts_feed", ["status", "created", "id"], unique=False)
        batch_op.create_index(
            "posts_owner_feed", ["owner", "created", "id"], unique=False
        )

    op.create_table(
        "reports",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("owner", sa.String(length=36), nullable=False),
        sa.Column("target_type", sa.String(length=16), nullable=False),
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("reason", sa.String(length=300), nullable=False),
        sa.Column("created", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(["owner"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("owner", "target_type", "target_id"),
    )
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.create_index("reports_queue", ["status", "created"], unique=False)

    op.create_table(
        "comments",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("post", sa.String(length=36), nullable=False),
        sa.Column("owner", sa.String(length=36), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("created", sa.BigInteger(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(["owner"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["post"], ["posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.create_index(
            "comments_thread", ["post", "status", "created", "id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_comments_owner"), ["owner"], unique=False)

    op.create_table(
        "likes",
        sa.Column("post", sa.String(length=36), nullable=False),
        sa.Column("owner", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["owner"], ["users.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["post"], ["posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("post", "owner"),
    )
    with op.batch_alter_table("likes", schema=None) as batch_op:
        batch_op.create_index("likes_owner", ["owner", "post"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("likes", schema=None) as batch_op:
        batch_op.drop_index("likes_owner")

    op.drop_table("likes")
    with op.batch_alter_table("comments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_comments_owner"))
        batch_op.drop_index("comments_thread")

    op.drop_table("comments")
    with op.batch_alter_table("reports", schema=None) as batch_op:
        batch_op.drop_index("reports_queue")

    op.drop_table("reports")
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.drop_index("posts_owner_feed")
        batch_op.drop_index("posts_feed")
        batch_op.drop_index("posts_category_feed")
        batch_op.drop_index(batch_op.f("ix_posts_owner"))

    op.drop_table("posts")
    with op.batch_alter_table("feedback", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_feedback_owner"))
        batch_op.drop_index("feedback_queue")

    op.drop_table("feedback")
    op.drop_table("blocks")
    op.drop_table("users")
    with op.batch_alter_table("rate_buckets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_rate_buckets_expires"))

    op.drop_table("rate_buckets")
    op.drop_table("audit")
    # ### end Alembic commands ###
