import {ReactNode} from 'react';
import {Text,View,StyleSheet,Pressable,ActivityIndicator,ScrollView,KeyboardAvoidingView,Platform} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
export const color={bg:'#111b15',card:'#1b2820',line:'#364a3b',text:'#e9f2eb',muted:'#a4b4a8',accent:'#bbd9c2',danger:'#ffb0a3'};
export const s=StyleSheet.create({page:{flex:1,backgroundColor:color.bg},content:{padding:20,gap:15,paddingBottom:35},title:{fontSize:27,fontWeight:'700',color:color.text},text:{fontSize:16,lineHeight:26,color:color.text},muted:{fontSize:13,lineHeight:21,color:color.muted},card:{backgroundColor:color.card,borderWidth:1,borderColor:color.line,borderRadius:14,padding:18,gap:10},input:{borderWidth:1,borderColor:color.line,borderRadius:9,padding:12,color:color.text,fontSize:16,backgroundColor:color.bg},row:{flexDirection:'row',alignItems:'center',gap:10,flexWrap:'wrap'},error:{color:color.danger,fontSize:14,lineHeight:22},label:{fontSize:14,fontWeight:'600',color:color.text},pill:{paddingHorizontal:12,paddingVertical:9,borderWidth:1,borderColor:color.line,borderRadius:18},pillOn:{backgroundColor:color.accent},pillText:{fontSize:12,color:color.muted},button:{backgroundColor:color.accent,borderRadius:9,paddingVertical:12,paddingHorizontal:16,alignItems:'center',minHeight:46},buttonText:{fontWeight:'700',color:color.bg,fontSize:14},secondary:{backgroundColor:'transparent',borderWidth:1,borderColor:color.line},secondaryText:{color:color.text},reply:{borderBottomWidth:1,borderBottomColor:color.line,paddingVertical:14,gap:8}});
export function Button({children,onPress,disabled=false,secondary=false}:{children:string;onPress:()=>void;disabled?:boolean;secondary?:boolean}){return <Pressable accessibilityRole="button" disabled={disabled} onPress={onPress} style={[s.button,secondary&&s.secondary,disabled&&{opacity:.5}]}><Text style={[s.buttonText,secondary&&s.secondaryText]}>{children}</Text></Pressable>}
export function Screen({children,scroll=true}:{children:ReactNode;scroll?:boolean}){return <SafeAreaView edges={['bottom','left','right']} style={s.page}><KeyboardAvoidingView style={{flex:1}} behavior={Platform.OS==='ios'?'padding':undefined}>{scroll?<ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={s.content}>{children}</ScrollView>:children}</KeyboardAvoidingView></SafeAreaView>}
export function Loading(){return <View style={[s.page,{justifyContent:'center',alignItems:'center'}]}><ActivityIndicator color={color.accent}/></View>}
export const when=(n:number)=>new Date(n).toLocaleString('zh-CN');
